export const CONTACT_FORM = 'CONTACT_FORM'
export const SEND_CONTACT_DATA: any = 'SEND_CONTACT_DATA'
export const SEND_CONTACT_DATA_ASYNC = 'SEND_CONTACT_DATA_ASYNC'
export const SENDED = 'SENDED'
export const SENDED_ASYNC = 'SENDED_ASYNC'

