export { default as fontQuery } from './fonts'
export { default as TestQuery } from './testQuery'
export { default as homePage } from './homePage'
export { default as footerQuery } from './footer'
export { default as headerQuery } from './header'
export { default as aboutPage } from './aboutPage'
export { default as portfolioPage } from './portfolioPage'
export { default as projectsQuery } from './projects'
