export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as GeneralButton } from './GeneralButton'
export { default as IconsButton } from './IconsButton'
export { default as Banner } from './Home/elements/Banner'
export { default as Footer } from './Footer'
export { default as SlideArrow } from './SlideArrow'
